version: '3'
services:
  frontend:
    build:
      context: ./tuiter-react-web-app-main
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=/api
      - PUBLIC_URL=/tuiter
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./tuiter-node-server-app-main
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb+srv://CS6510:CS6510@cluster0.zpnb3.mongodb.net/tuiter?retryWrites=true&w=majority&appName=Cluster0
      - PORT=4000
    command: ["node", "app.js"]
    volumes:
      - ./tuiter-node-server-app-main/public/images:/app/public/images

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  mongodb:
    image: mongo:5.0
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: